services:
  localstack:
    image: localstack/localstack:4
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,apigateway,sqs,sns,dynamodb,s3,stepfunctions,cloudwatch,iam
      - DEBUG=0
      - AWS_DEFAULT_REGION=eu-central-1
    volumes:
      - localstack_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_pass
      POSTGRES_DB: orders_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  localstack_data:
